name: common commit

on:
  push:
    paths:
      - .github/workflows/common.yaml
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'main'
      - 'develop'

  jobs:
    tests:
      name: run tests
      runs-on: ubuntu-latest

      defaults:
        run:
          working-directory: ./src

      steps:
        - uses: actions/checkout@v3

        - name: cp env
          run: cp .env.testing .env

