name: common commit

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'main'
      - 'develop'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: copy .env
        run: cp .env.example .env

      - name: docker build
        run: docker-compose build

      - name: docker up -d
        run: docker-compose up -d
