name: common commit

on:
  push:
    paths:
      - .github/workflows/common.yaml
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'
      - 'main'
      - 'develop'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

